version: "3.8"

services:
  postgres:
    image: postgres:16.0-alpine3.18
    restart: always
    env_file:
      - .env/.env.postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env/.env.backend
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  postgres: